---
title: "Concordance method comparison"
author: "Matt Ploenzke"
date: "12/7/2019"
output: html_document:
  toc: true
  toc_float: true
  code_folding: hide 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages.
```{r}
library(readxl)
library(tidyverse)
library(PharmacoGx)
```

Set options for the run.
```{r}
min_posterior_probability_sensitive <- .5
comparison <- 'CCLE_GDSC'
run_on_cluster <- FALSE
base_log_dir <- paste(comparison,'concordance',sep='_')
dir.create(base_log_dir,showWarnings = FALSE)
```

Load posteriors.
```{r}
if (!run_on_cluster) {
  individual_posteriors <- readRDS(file.path('~/Desktop/Concordance/tidyPharmaco',
                                             paste(comparison,'_fit_p60',sep=''),
                                             'posterior.formatted.RDS'))
} else {
  individual_posteriors <- readRDS(file.path('~/concordance',
                                             paste(comparison,'_fit_p60',sep=''),
                                             'posterior.formatted.RDS'))
}
```

Pull list of drugs to assess. 
```{r}
all_drugs <- individual_posteriors %>% 
  group_by(drug) %>% 
  distinct(experiment) %>% 
  filter(n()>1) %>% 
  ungroup() %>% 
  distinct(drug) %>% 
  #filter(row_number()==1) %>%
  pull(drug) 
broad_drugs <- c('17-AAG','paclitaxel','PD-0325901','AZD6244')
posterior <- individual_posteriors %>% select(cell, drug, experiment, posterior_probability_sensitive)
datasets <- posterior %>% distinct(experiment) %>% pull()
```

Set up Y data matrices, one per study.
```{r}
rez <- tibble()
for (dataset in datasets) {
  print(dataset)
    if (!run_on_cluster) {
    load(file.path('~/Desktop/Concordance/PSets',paste(dataset,'RData',sep='.')))
  } else {
    load(file.path('~/concordance/PSets',paste(dataset,'RData',sep='.')))
  }
  eval(parse(text = paste('tempPset <- ',dataset,sep='')))
  y_new_temp <- summarizeSensitivityProfiles(tempPset, sensitivity.measure = 'auc_recomputed', summary.stat = 'median', verbose = FALSE) %>%
    as.data.frame() %>%
    rownames_to_column('drug') %>%
    as_tibble() %>% 
    gather(key='cell',value='value',-drug) %>%
    group_by(drug) %>%
    filter(!is.na(value)) %>%
    mutate(waterfall=PharmacoGx:::callingWaterfall(value,type='AUC')) %>%
    ungroup() %>% 
    rename(auc_recomputed=value) %>%
    mutate(experiment = dataset)
  
  y_new_temp <- y_new_temp %>% 
    inner_join(posterior %>% distinct(),by=c('cell','experiment','drug')) %>%
    mutate(cell_type = case_when(posterior_probability_sensitive > min_posterior_probability_sensitive ~ 'sensitive',
                             TRUE ~ 'resistant'))
  rez <- rez %>% bind_rows(y_new_temp)
  eval(parse(text=paste('rm(',dataset,',tempPset, y_new_temp)',sep='')))
}
```

Calculate AAC MCC and naive MCC.
```{r}
all_MCCs <- rez %>% 
  #filter(drug=='17-AAG') %>%
  select(experiment, drug, cell,auc_recomputed) %>% 
  crossing(tibble(threshold=seq(.01,.99,by=.01))) %>%
  mutate(called = case_when(auc_recomputed >= threshold ~ 'sensitive', 
                            TRUE ~ 'resistant')) %>%
  select(-auc_recomputed) %>%
  spread(experiment, called) %>% 
  na.omit() %>%
  select(-cell) %>%
  group_by(drug, threshold) %>%
  summarise(t00 = sum(CCLE=='resistant' &  GDSC=='resistant'),
            t11 = sum(CCLE=='sensitive' &  GDSC=='sensitive'),
            t01 = sum(CCLE=='resistant' &  GDSC=='sensitive'),
            t10 = sum(CCLE=='sensitive' &  GDSC=='resistant')) %>%
   mutate(t00 = t00+.5,
          t11 = t11+.5,
          t10 = t10+.5,
          t01 = t01+.5) %>% 
   ungroup() %>%
   mutate(MCC = (t00*t11-t01*t10)/sqrt((t11+t01)*(t11+t10)*(t00+t10)*(t00+t01)))
aac_best_MCCs <- all_MCCs %>%
  group_by(drug) %>%
  filter(MCC == max(MCC)) %>% 
  filter(row_number()==1) %>%
  ungroup() %>% 
  select(drug, threshold, MCC) %>%
  mutate(method = 'best',
         measure = 'AAC')
aac_naive_MCCs <- all_MCCs %>%
  group_by(drug) %>%
  filter((threshold == .2 & !(drug %in% broad_drugs)) | (threshold == .4 & drug %in% broad_drugs)) %>% 
  ungroup() %>% 
  select(drug, threshold, MCC) %>%
  mutate(method = 'naive',
         measure = 'AAC')
```

Calculate waterfall MCC.
```{r}
waterfall_MCCs <- rez %>% 
  filter(waterfall!='intermediate') %>%
  select(experiment, drug, cell,waterfall) %>% 
  spread(experiment, waterfall) %>% 
  na.omit() %>%
  select(-cell) %>%
  group_by(drug) %>%
  summarise(t00 = sum(CCLE=='resistant' &  GDSC=='resistant'),
            t11 = sum(CCLE=='sensitive' &  GDSC=='sensitive'),
            t01 = sum(CCLE=='resistant' &  GDSC=='sensitive'),
            t10 = sum(CCLE=='sensitive' &  GDSC=='resistant')) %>%
   mutate(t00 = t00+.5,
          t11 = t11+.5,
          t10 = t10+.5,
          t01 = t01+.5) %>% 
   ungroup() %>%
   mutate(MCC = (t00*t11-t01*t10)/sqrt((t11+t01)*(t11+t10)*(t00+t10)*(t00+t01))) %>%
  select(drug, MCC) %>%
  mutate(method = 'best',
         measure = 'waterfall')
```

Calculate posterior MCC.
```{r}
all_MCCs <- rez %>% 
  #filter(drug=='17-AAG') %>%
  select(experiment, drug, cell,posterior_probability_sensitive) %>% 
  crossing(tibble(threshold=seq(.01,.99,by=.01))) %>%
  mutate(called = case_when(posterior_probability_sensitive >= threshold ~ 'sensitive', 
                            TRUE ~ 'resistant')) %>%
  select(-posterior_probability_sensitive) %>%
  spread(experiment, called) %>% 
  na.omit() %>%
  select(-cell) %>%
  group_by(drug, threshold) %>%
  summarise(t00 = sum(CCLE=='resistant' &  GDSC=='resistant'),
            t11 = sum(CCLE=='sensitive' &  GDSC=='sensitive'),
            t01 = sum(CCLE=='resistant' &  GDSC=='sensitive'),
            t10 = sum(CCLE=='sensitive' &  GDSC=='resistant')) %>%
   mutate(t00 = t00+.5,
          t11 = t11+.5,
          t10 = t10+.5,
          t01 = t01+.5) %>% 
   ungroup() %>%
   mutate(MCC = (t00*t11-t01*t10)/sqrt((t11+t01)*(t11+t10)*(t00+t10)*(t00+t01)))
posterior_best_MCCs <- all_MCCs %>%
  group_by(drug) %>%
  filter(MCC == max(MCC)) %>% 
  filter(row_number()==1) %>%
  ungroup() %>% 
  select(drug, threshold, MCC) %>%
  mutate(method = 'best',
         measure = 'posterior')
posterior_naive_MCCs <- all_MCCs %>%
  group_by(drug) %>%
  filter(threshold==min_posterior_probability_sensitive) %>% 
  ungroup() %>% 
  select(drug, threshold, MCC) %>%
  mutate(method = 'naive',
         measure = 'posterior')
```

Pearson correlation.
```{r}
aac_corrs <- rez %>% 
  select(experiment, drug, cell,auc_recomputed) %>% 
  spread(experiment, auc_recomputed) %>% 
  na.omit() %>%
  select(-cell) %>%
  group_by(drug) %>%
  summarise(pearson = cor(CCLE, GDSC, method='pearson'),
            spearman = cor(CCLE, GDSC, method='spearman')) %>%
  ungroup() %>%
  gather('method','MCC', -drug) %>%
  mutate(measure = 'AAC')
posterior_corrs <- rez %>% 
  select(experiment, drug, cell, posterior_probability_sensitive) %>% 
  spread(experiment, posterior_probability_sensitive) %>% 
  na.omit() %>%
  select(-cell) %>%
  group_by(drug) %>%
  summarise(pearson = cor(CCLE, GDSC, method='pearson'),
            spearman = cor(CCLE, GDSC, method='spearman')) %>%
  ungroup() %>%
  gather('method','MCC', -drug) %>%
  mutate(measure = 'posterior')
```

Join them all.
```{r}
all_agreements <- aac_best_MCCs %>% 
  bind_rows(aac_naive_MCCs) %>%
  bind_rows(waterfall_MCCs) %>%
  bind_rows(posterior_naive_MCCs) %>%
  bind_rows(posterior_best_MCCs) %>% 
  bind_rows(aac_corrs) %>%
  bind_rows(posterior_corrs)
```

Plot it.
```{r}
all_agreements %>% 
  mutate(broad = case_when(drug %in% broad_drugs ~ 'Broad drugs',
                           TRUE ~ 'Targeted drugs'),
         continuous = case_when(method %in% c('pearson','spearman') ~  'Continuous agreement',
                                TRUE ~ 'Binary agreement'),
         method = case_when(method == 'best' ~ 'Best MCC',
                            method == 'naive' ~ 'Naive MCC',
                            method == 'pearson' ~ 'Pearson correlation',
                            method == 'spearman' ~ 'Spearman correlation')) %>%
  filter(broad == 'Targeted drugs') %>%
  ggplot(aes(x=drug, y=MCC, fill=measure)) + 
  geom_bar(stat='identity', position='dodge') + 
  facet_wrap(vars(method), nrow=2) + 
  theme_bw() + 
  scale_fill_brewer(palette='Dark2') + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        legend.position = 'top') + 
  labs(fill='')

all_agreements %>% 
  mutate(broad = case_when(drug %in% broad_drugs ~ 'Broad drugs',
                           TRUE ~ 'Targeted drugs'),
         continuous = case_when(method %in% c('pearson','spearman') ~  'Continuous agreement',
                                TRUE ~ 'Binary agreement'),
          method = case_when(method == 'best' ~ 'Best MCC',
                            method == 'naive' ~ 'Naive MCC',
                            method == 'pearson' ~ 'Pearson correlation',
                            method == 'spearman' ~ 'Spearman correlation')) %>%
  filter(broad == 'Broad drugs') %>%
  ggplot(aes(x=drug, y=MCC, fill=measure)) + 
  geom_bar(stat='identity', position='dodge') + 
  facet_wrap(vars(method), nrow=2) + 
  theme_bw() + 
  scale_fill_brewer(palette='Dark2') + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        legend.position = 'top') + 
  labs(fill='')
```

