---
title: "Untitled"
author: "Matt Ploenzke"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages.
```{r}
library(tidyverse)
library(ggrepel)
library(magrittr)
```

Load correlations between estimated effect sizes.
```{r}
CCLE_GDSC_rna <- read_csv('~/Desktop/Concordance/results/CCLE_GDSC_biomarkers_rna/correlations.csv')
CCLE_GDSC_cnv <- read_csv('~/Desktop/Concordance/results/CCLE_GDSC_biomarkers_cnv/correlations.csv')
CCLE_GDSC_mutation <- read_csv('~/Desktop/Concordance/results/CCLE_GDSC_biomarkers_mutation/correlations.csv')
CCLE_GDSC_rna2 <- read_csv('~/Desktop/Concordance/results/CCLE_GDSC_biomarkers_rna2/correlations.csv')
CCLE_GDSC <- CCLE_GDSC_rna %>%
  mutate(Feature = 'RNA') %>%
  bind_rows(CCLE_GDSC_cnv %>% mutate(Feature = 'CNV')) %>%
  bind_rows(CCLE_GDSC_mutation %>% mutate(Feature = 'Mutation')) %>%
  bind_rows(CCLE_GDSC_rna2 %>% mutate(Feature = 'RNA2'))
rm(CCLE_GDSC_rna, CCLE_GDSC_cnv, CCLE_GDSC_mutation, CCLE_GDSC_rna2)
```

Correlation between effect sizes comparison.
```{r}
broad_drugs <- c('17-AAG','paclitaxel','PD-0325901','AZD6244')
CCLE_GDSC %>%
  filter((Method=='Continuous' & Drug %in% broad_drugs) | (Method=='Binarized' & !(Drug %in% broad_drugs))) %>%
  filter(!str_detect(Comparison,'Joint')) %>%
  #filter(Feature == 'RNA') %>%
  rename(Value = logFC_correlation) %>%
  select(Method, Measure, Drug, Comparison, Feature, Value) %>%
  spread(Measure, Value) %>%
  mutate(color = case_when(Posterior-AAC>0 ~ 'blue',
                           Posterior==AAC ~' grey',
                           Posterior<AAC ~ 'red')) %>%
  ggplot(aes(x=AAC,y=Posterior,label=Drug, color=color)) + 
  geom_point() + 
  geom_abline(aes(slope=1,intercept=0),lty=2) + 
  geom_hline(aes(yintercept=0), color='grey',lty=1) + 
  geom_vline(aes(xintercept=0), color='grey',lty=1) + 
  geom_label_repel() +
  facet_grid(cols = vars(Feature), scales='free') + 
  theme_bw() + 
  ylim(-1,1) + 
  xlim(-1,1) + 
  theme(legend.position = 'none') + 
  scale_color_manual(values=c('red'='red','blue'='blue','grey'='grey')) + 
  labs(x='Raw values',y='Model fit', 
       title='Model fit improves agreement betweeen biomarker effect sizes',
       subtitle = 'Pearson correlation between effect sizes of gene expression for all commonly-tested compounds',
       caption = 'Models fit independently to CCLE and GDSC datasets. Data curated from PharmacoGx.')
ggsave(filename='correlation_between_effect_sizes.pdf',width=8,height=4.5,units='in')
```

Same thing.
```{r}
broad_drugs <- c('17-AAG','paclitaxel','PD-0325901','AZD6244')
CCLE_GDSC %>%
  filter((Method=='Continuous' & Drug %in% broad_drugs) | (Method=='Binarized' & !(Drug %in% broad_drugs))) %>%
  filter(!str_detect(Comparison,'Joint')) %>%
  #filter(Feature == 'RNA') %>%
  rename(Value = logFC_correlation) %>%
  select(Method, Measure, Drug, Comparison, Feature, Value) %>%
  spread(Measure, Value) %>%
  mutate(color = case_when(Posterior-AAC>0 ~ 'blue',
                           Posterior==AAC ~' grey',
                           Posterior<AAC ~ 'red')) %>%
  ggplot(aes(x=AAC,y=Posterior,label=Drug, shape=Feature)) + 
  geom_point(aes(color=color),size=3, alpha=.8) + 
  geom_abline(aes(slope=1,intercept=0),lty=2) + 
  geom_hline(aes(yintercept=0), color='grey',lty=1) + 
  geom_vline(aes(xintercept=0), color='grey',lty=1) + 
  theme_bw() + 
  theme(legend.position = 'bottom',panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  guides(color = FALSE) +
  scale_color_manual(values=c('red'='red','blue'='blue','grey'='grey')) + 
  labs(x='AAC-based',y='Model-based', 
       title='Model fit improves agreement betweeen biomarker effect sizes',
       subtitle = 'Pearson correlation between effect sizes of gene expression for all commonly-tested compounds')
ggsave(filename='correlation_between_effect_sizes.pdf',width=8,height=8,units='in')
```

Load all estimated effect sizes from RNA.
```{r}
all_effect_sizes <- read_csv('~/Desktop/Concordance/results/CCLE_GDSC_biomarkers_rna/all_effect_sizes.csv') %>%
  mutate(Feature = 'RNA') %>%
  bind_rows(read_csv('~/Desktop/Concordance/results/CCLE_GDSC_biomarkers_cnv/all_effect_sizes.csv') %>%
  mutate(Feature = 'CNV')) %>%
  bind_rows(read_csv('~/Desktop/Concordance/results/CCLE_GDSC_biomarkers_mutation/all_effect_sizes.csv') %>%
  mutate(Feature = 'Mutation'))
drug_types <- readRDS('~/Desktop/Concordance/results/CCLE_GDSC_fit_joint/posterior_drug_fits.RDS') %>%
  distinct(drug, drug_type)

all_effect_sizes <- all_effect_sizes %>%
  left_join(drug_types, by=c('Drug'='drug'))
```

Volcano plots.
```{r}
plot_dat <- all_effect_sizes %>% 
 filter(Drug %in% c('Nilotinib','Sorafenib',
                     'PLX4720','PHA-665752','Nutlin-3',
                     'PD-0332991','Crizotinib','Erlotinib',
                     'AZD0530','TAE684','AZD6244',
                     'paclitaxel','17-AAG','lapatinib','PD-0325901')) %>% 
  filter((Measure=='Posterior' & Dataset=='Joint'& Method=='Binarized' & !(Drug %in% broad_drugs)) | 
         (Measure=='Posterior' & Dataset=='Joint'& Method=='Continuous' & Drug %in% broad_drugs) |
           (Measure=='AAC' & Method=='Continuous')) %>%
  group_by(Drug) %>% 
  mutate(num_known = n_distinct(isKnown)) %>%
  ungroup() %>%
  filter(num_known > 1) %>%
  select(symbol, Feature, type, Measure, logFC, AveExpr, t, adj.P.Val, Drug, isKnown) %>% 
  mutate(alpha = ifelse(isKnown,.9,.01)) %>%
  mutate(capped_p = pmin(-log10(adj.P.Val),5),
         hline = -log10(.05)) 
plot_dat %>%
  ggplot(aes(x=logFC,y=capped_p)) + 
  geom_hline(aes(yintercept=0)) + 
  geom_hline(aes(yintercept=hline),lty=2) + 
  geom_point(data = plot_dat %>% filter(!isKnown), aes(alpha=alpha,fill=isKnown), show.legend = FALSE,pch=21,color='black') + 
  geom_point(data = plot_dat %>% filter(isKnown), aes(alpha=alpha,fill=isKnown), show.legend = FALSE,pch=21,color='black') + 
  theme_bw() + 
  facet_grid(rows=vars(Measure),cols=vars(Drug),scales='free_x') + 
  scale_fill_manual(values=c('FALSE'='grey','TRUE'='red')) + 
  theme(legend.position='none',panel.grid.major = element_blank(), panel.grid.minor = element_blank())  + 
  labs(x='log(Fold Chance)',y='-log10(Adjusted P-value)', 
       caption = 'Models fit jointly to CCLE and GDSC datasets. Data curated from PharmacoGx.')

  ggsave(filename='plot.png',width=18,height=6,units='in')
```

Bar plot of number significant by method for individual datasets - they appear in equal numbers.
```{r}
all_effect_sizes %>% 
  filter(!is.na(type)) %>%
  filter(Drug %in% c('Nilotinib','Sorafenib',
                     'PLX4720','PHA-665752','Nutlin-3',
                     'PD-0332991','Crizotinib','Erlotinib',
                     'AZD0530','TAE684','AZD6244',
                     'paclitaxel','17-AAG','lapatinib','PD-0325901')) %>% 
  filter((Measure=='Posterior' & Dataset!='Joint'& Method=='Binarized' & !(drug_type=='broad')) | 
         (Measure=='Posterior' & Dataset!='Joint'& Method=='Continuous' & (drug_type=='broad')) |
           (Measure=='AAC' & Method=='Continuous' & Dataset!='Joint' & (drug_type=='broad')) |
           (Measure=='AAC' & Method=='Binarized' & Dataset!='Joint' & !(drug_type=='broad'))) %>% 
  mutate(drug_type = case_when(drug_type=='broad' ~ 'Broad',
                               TRUE ~ 'Targeted')) %>%
  group_by(Measure, type, Method, drug_type, Dataset) %>%
  summarise(isSignificant  = sum(adj.P.Val<=.05)) %>%
  ungroup() %>%
  mutate(Measure=case_when(Measure == 'AAC' ~ 'AAC-based',TRUE ~ 'Model-based')) %>%
  ggplot(aes(x=drug_type, y=isSignificant, fill=Measure)) + 
  geom_bar(stat='identity', position='dodge') +
  facet_grid(rows=vars(type), cols=vars(Dataset), scales='free_y') + 
  theme_bw() + 
  scale_fill_grey() + 
  theme(legend.position='bottom') +
  labs(x='', y='',title = 'Count of significant biomarkers by method',fill='') 
ggsave(filename='plot.pdf',width=6,height=6,units='in')
```

Count of known biomarkers which were found.
```{r}
all_effect_sizes %>% 
  filter(!is.na(type)) %>%
  filter(Drug %in% c('Nilotinib','Sorafenib',
                     'PLX4720','PHA-665752','Nutlin-3',
                     'PD-0332991','Crizotinib','Erlotinib',
                     'AZD0530','TAE684','AZD6244',
                     'paclitaxel','17-AAG','lapatinib','PD-0325901')) %>% 
  filter((Measure=='Posterior' & Dataset!='Joint'& Method=='Binarized' & !(drug_type=='broad')) | 
         (Measure=='Posterior' & Dataset!='Joint'& Method=='Continuous' & (drug_type=='broad')) |
           (Measure=='AAC' & Method=='Continuous' & Dataset!='Joint' & (drug_type=='broad')) |
           (Measure=='AAC' & Method=='Binarized' & Dataset!='Joint' & !(drug_type=='broad'))) %>% 
  mutate(drug_type = case_when(drug_type=='broad' ~ 'Broad',
                               TRUE ~ 'Targeted')) %>%
  group_by(Measure, type, Method, drug_type, Dataset) %>%
  summarise(isRelevant = sum(adj.P.Val<=.05 & isKnown)) %>%
  ungroup() %>% 
  mutate(Measure=case_when(Measure == 'AAC' ~ 'AAC-based',TRUE ~ 'Model-based')) %>%
  ggplot(aes(x=drug_type, y=isRelevant, fill=Measure)) + 
  geom_bar(stat='identity', position='dodge') +
  facet_grid(rows=vars(type), cols=vars(Dataset), scales='free_y') + 
  theme_bw() + 
  scale_fill_grey() + 
  theme(legend.position='bottom') + 
  labs(x='', y='',title = 'Count of known significant biomarkers by method',fill='')
ggsave(filename='plot.pdf',width=6,height=6,units='in')
```


