---
title: "Pathway plots"
author: "Matt Ploenzke"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages.
```{r}
library(tidyverse)
library(ggrepel)
```

Load pathway output.
```{r}
pathway_path <- '~/Desktop/Concordance/results/CCLE_GDSC1000_CTRPv2_FIMM_gCSI_pathway_rna_2/'
drugs <- list.dirs(pathway_path,full.names=FALSE)
drugs <- drugs[drugs!='']
GO_tibble <- tibble()
KEGG_tibble <- tibble()
for (dr in drugs) {
  filles <- list.files(file.path(pathway_path,dr))
  for (fi in filles) {
    if (grepl('GO',fi)) { 
      GO_tibble <- read_csv(file.path(pathway_path,dr,fi)) %>%
        as_tibble() %>%
        mutate(File=fi, Drug=dr) %>%
        bind_rows(GO_tibble)
    } else if (grepl('KEGG',fi)) { 
      KEGG_tibble <- read_csv(file.path(pathway_path,dr,fi)) %>%
        as_tibble() %>%
        mutate(File=fi, Drug=dr) %>%
        bind_rows(KEGG_tibble)
    }
  }
}
```

Format GO and KEGG results.
```{r}
GO_tibble <- GO_tibble %>%
  mutate(File = gsub('GO_','',File)) %>%
  mutate(File = gsub('.csv','',File)) %>%
  separate(File,  into=c('Measure','Measure2','Dataset'),sep='_',fill='right',remove=TRUE) %>% 
  select(-Measure2) %>% 
  mutate(Dataset =  case_when((Dataset=='sensitive' | is.na(Dataset)) ~ 'Joint',
                              TRUE ~ Dataset)) %>%
  mutate(Measure = case_when(Measure == 'auc' ~ 'AAC',
                             Measure == 'posterior'  ~ 'Posterior',
                             Measure == 'cell'  ~ 'Cell type',
                             Measure == 'naive' ~ 'Naive'))

KEGG_tibble <- KEGG_tibble %>%
  mutate(File = gsub('KEGG_','',File)) %>%
  mutate(File = gsub('.csv','',File)) %>%
  separate(File,  into=c('Measure','Measure2','Dataset'),sep='_',fill='right',remove=TRUE) %>% 
  select(-Measure2) %>% 
  mutate(Dataset =  case_when((Dataset=='sensitive' | is.na(Dataset)) ~ 'Joint',
                              TRUE ~ Dataset)) %>%
  mutate(Measure = case_when(Measure == 'auc' ~ 'AAC',
                             Measure == 'posterior'  ~ 'Posterior',
                             Measure == 'cell'  ~ 'Cell type',
                             Measure == 'naive' ~ 'Naive'))

```

Plot KEGG results for all studies and methods.
```{r}
plot_tibble <- KEGG_tibble %>%
  filter(Measure %in% c("Naive", "Cell type")) %>%
  unite(Measure, Measure, Dataset, sep=' ') %>%
  #filter(P.Up<.05 | P.Down<.05) %>% 
  mutate(P=pmin(P.Up, P.Down)) %>%
  mutate(Up = case_when(P.Up < P.Down ~ 'Up',
                        TRUE ~ 'Down')) %>%
  group_by(Measure, Drug,Up) %>% 
  arrange(P) %>%
  mutate(Label = case_when(row_number()<=5 ~ Pathway,
                           TRUE ~ '')) %>%
  ungroup() 
plot_tibble %>%
  ggplot(aes(x=N,y=-log10(P),color=Up, label=Label)) + 
  geom_point(alpha=.1) + 
  geom_text_repel() +
  facet_grid(rows=vars(Measure), cols = vars(Drug), scales='free') + 
  theme_bw() +
  theme(legend.position='top') +
  scale_color_brewer(palette='Dark2')
```

Two-way plot comparing methods for KEGG.
```{r}
plot_dat <- KEGG_tibble %>% 
  filter(Measure %in% c("Naive", "Cell type"), Dataset=='Joint') %>%
  unite(Measure, Measure, Dataset, sep=' ') %>%
  mutate(P=pmin(P.Up, P.Down)) %>%
  mutate(Up = case_when(P.Up < P.Down ~ 'Up',
                        TRUE ~ 'Down')) %>%
  select(Pathway, Measure, P, Drug) %>% 
  arrange(P) %>%
  distinct(Pathway, Measure, Drug, .keep_all = TRUE) %>%
  mutate(P = -log10(P)) %>%
  spread(Measure, P) %>% 
  replace_na(list(`Naive Joint`=0, `Cell type Joint`=0)) %>%
  rename(Comparison = `Naive Joint`) %>%
  rename(myMethod = `Cell type Joint`) 

plot_dat %>%
    mutate(color = case_when(str_detect(Pathway,'kinase') |  
                               str_detect(Pathway,'JAK') | 
                               str_detect(Pathway,'ALK') | 
                               str_detect(Pathway, "Pathways in cancer") |
                               str_detect(Pathway, "Antineoplastic") |
                               str_detect(Pathway, "Non-small cell lung cancer") ~ 5,
                           Comparison>= -log10(.05) & myMethod < -log10(.05) ~ 1,
                           Comparison< -log10(.05) & myMethod>= -log10(.05) ~ 2,
                           Comparison >= -log10(.05) | myMethod>= -log10(.05) ~ 3,
                           TRUE ~ 4)) %>% 
  mutate(Pathway = case_when(color == 5 ~ Pathway,
                             Comparison>= -log10(1e-3) ~Pathway,
                             myMethod >= -log10(1e-5) ~ Pathway,
                             TRUE ~ '')) %>%
  ggplot(aes(x=Comparison, y=myMethod, color=as.factor(color))) + 
  geom_vline(aes(xintercept=0)) + 
  geom_hline(aes(yintercept=0)) + 
  geom_abline(aes(slope=1,intercept=0)) + 
  geom_point(aes(shape=as.factor(color))) + 
  geom_text_repel(aes(label=Pathway), size=3) + 
  theme_bw()+ 
  theme(legend.position='none', panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_colour_manual(values = c("5" = "red", "4" = "grey40", "3" = "grey40", "1" = "grey40","2" = "grey40")) + 
  labs(x='AAC-based -log10(P-value)', y='Model-based -log10(P-value)')
ggsave('plot.png',width=6,height=6,units='in')
```

Same thing for joint dataset.
```{r}
tdat <- KEGG_tibble %>% 
  filter(Measure %in% c("Naive", "Cell type"), Dataset=='Joint') %>%
  unite(Measure, Measure, Dataset, sep=' ') %>% 
  mutate(P=pmin(P.Up, P.Down)) %>%
  mutate(Up = case_when(P.Up < P.Down ~ 'Up',
                        TRUE ~ 'Down')) %>%
  mutate(P = -log10(P)) %>%
  #mutate(P = case_when(Up == 'Up' ~ P, TRUE ~ -P)) %>%
  select(Pathway, Measure, P, Drug) %>% 
  arrange(desc(P)) %>%
  distinct(Pathway, Measure, Drug, .keep_all = TRUE) %>%
  spread(Measure, P) %>% 
  replace_na(list(`Naive Joint`=0, `Cell type Joint`=0)) %>%
  rename(AAC = `Naive Joint`) %>%
  rename(Posterior = `Cell type Joint`) %>%
  mutate(color = case_when(str_detect(Pathway,'kinase') |  
                           str_detect(Pathway,'JAK') | 
                           str_detect(Pathway,'ALK') | 
                           str_detect(Pathway, "Pathways in cancer") |
                           str_detect(Pathway, "Antineoplastic") |
                           str_detect(Pathway, "Non-small cell lung cancer") ~ 'Mechanistic Kegg Pathways',
                           str_detect(Pathway, 'Focal adhesion') | 
                           str_detect(Pathway, 'ECM-receptor') | 
                           str_detect(Pathway, 'Axon') | 
                           str_detect(Pathway, 'Proteoglycans') ~ 'Cell Matrix Pathways',
                           str_detect(Pathway, 'Th17') |
                           str_detect(Pathway, 'Th1') |
                           str_detect(Pathway, 'T-cell') ~ 'T cell', 
                           str_detect(Pathway, 'Natural killer') ~ 'Cytotoxicity', 
                           str_detect(Pathway, 'PD-L1') ~ 'Checkpoint pathway in cancer',
                           TRUE ~ 'Other')) %>% 
  mutate(color = case_when(color=='Mechanistic Kegg Pathways' ~ 'red',
                           TRUE ~ 'grey')) %>%
  mutate(label = case_when(color == 'grey' ~ 'transparent',
                           color == 'red' ~ 'red',
                           TRUE ~ 'black')) %>%
  #filter(abs(Posterior)>=.05 | abs(AAC)>=.05) %>%
  arrange(Posterior) %>%
  mutate(yy=row_number())
tdat %>%
  ggplot(aes(x=AAC, xend=Posterior,
             y=reorder(Pathway,yy),yend=reorder(Pathway,yy),
             color=color)) + 
  geom_vline(aes(xintercept=0),lty=1) + 
  geom_vline(aes(xintercept=-log10(.05)),lty=2) + 
  geom_segment(arrow=arrow(angle=20, length=unit(.25,'cm')), alpha=.5) + 
  theme_bw() + 
  labs(x='-log10(P-value)', y='') + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        axis.ticks.y = element_blank(),
        axis.text.y = element_text(color=tdat$label),
        axis.line.x = element_line(colour = "black")) +
  scale_color_manual(values=c('red'='red','grey'='grey')) + 
  scale_x_continuous(expand=c(0,0))
ggsave('plot.pdf',width=12,height=8.5,units='in')
```

Comparison of p-values for known biomarkers.
```{r}
all_effect_sizes <- read_csv('~/Desktop/Concordance/results/CCLE_GDSC1000_CTRPv2_FIMM_gCSI_biomarkers_rna/all_effect_sizes.csv') %>% 
  filter(Drug=='Crizotinib')  %>%
  filter(Method == 'Binarized') %>%
  filter((Dataset=='Joint' & Measure=='Posterior') | Measure=='AAC') %>%
  distinct()

all_effect_sizes %>% 
  filter(isKnown) %>%
  mutate(symbol = case_when(-log10(adj.P.Val) > .5 ~ symbol, TRUE ~ '')) %>%
  ggplot(aes(x=logFC,y=-log10(adj.P.Val), color=Measure)) + 
  geom_hline(aes(yintercept=-log10(.05)),lty=2, color='black') +
  geom_hline(aes(yintercept=0), lty=1, color='black') +
  geom_point() + 
  geom_text_repel(aes(label=symbol), size=3,show.legend=FALSE) + 
  theme_bw() + 
  theme(legend.position=c(.25,.85), 
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.background = element_rect(size=0.5, linetype="solid",color='black')) + 
  labs(color='Sensitivity measure') + 
  scale_color_viridis_d(option = "viridis", end=.5) 
ggsave('plot.png',width=3.25,height=6,units='in')
```

Known biomarkers shown with arrows.
```{r}
all_effect_sizes %>% 
  filter(isKnown) %>%
  select(symbol, Feature, t, Measure) %>%
  spread(Measure, t) %>% 
  replace_na(list(AAC=0, Posterior=0)) %>%
  arrange(Posterior) %>%
  mutate(yy=row_number(),
         color = (Posterior>AAC & Posterior>=0) | (Posterior<AAC & Posterior<=0)) %>%
  ggplot(aes(x=AAC, xend=Posterior,
             y=reorder(symbol,yy),yend=reorder(symbol,yy),
             color = color)) + 
  geom_vline(aes(xintercept=0),lty=1) + 
  geom_vline(aes(xintercept=-3),lty=2,alpha=.2) + 
  geom_vline(aes(xintercept=3),lty=2,alpha=.2) + 
  geom_segment(arrow=arrow(angle=20, length=unit(.25,'cm'))) + 
  theme_bw() + 
  labs(x='Test statistic', y='Gene') + 
  lims(x=c(-3.5,7.5)) + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.background = element_rect(size=0.5, linetype="solid",color='black'),
        legend.position = 'none') + 
  scale_color_viridis_d(option = "viridis", end=.5) 
ggsave('plot.pdf',width=4,height=6,units='in')
```

