---
title: "Make figures"
author: "Matt Ploenzke"
date: "2/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages needed.
```{r}
rm(list=ls(all=TRUE))
library(tidyverse)
library(cowplot)
```

Figure 1.
```{r}
p1 <- readRDS('Figs/Fig1/17-AAG_639-V.RDS') + theme(plot.title=element_blank(),
                                                    plot.subtitle = element_blank(),
                                                    axis.ticks = element_blank(),
                                                    axis.text.x=element_blank(),
                                                    axis.text.y=element_blank(),
                                                    axis.title = element_text(size = 14),
                                                    axis.text = element_text(size = 12)) + 
  geom_hline(aes(yintercept=100),lty=1,lwd=.8,alpha=.5) + 
  geom_hline(aes(yintercept=0),lty=1,lwd=.8,alpha=.5) + 
  labs(x = expression(paste("Concentration (", log10, " ", mu, "M)",sep='')),
       y='Relative Viability') + 
  scale_y_continuous(breaks=c(0,100),labels=c('0','1'))

p2 <- readRDS('Figs/Fig1/boxplot_raw_all_cells.RDS') + 
  labs(y='AOC') + 
  theme(axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 10,angle=20),
        axis.title.y = element_text(size=14),
        legend.position = c(.4,.9),
        legend.title = element_blank(),
        legend.text = element_text(size=12)) +
  scale_fill_brewer(palette='Accent')

p3 <- readRDS('Figs/Fig1/Spearman_Pearson_CCLE_GDSC.RDS') + 
  scale_color_brewer(palette = 'Dark2') + 
  theme(legend.position = 'none') + 
  theme(axis.title = element_text(size = 14),
        plot.title = element_text(size=14),
        axis.text = element_text(size = 12)) + 
  ggtitle('Pairwise study agreement') +
  geom_hline(aes(yintercept=0),lty=2,lwd=.8,alpha=.5) +
  geom_vline(aes(xintercept=0),lty=2,lwd=.8,alpha=.5)

p4 <- readRDS('Figs/Fig1/17-AAG_posterior_CCLE_GDSC.RDS') + 
  theme(legend.position = c(.1,.65), plot.title=element_blank()) +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12))
p5 <- readRDS('Figs/Fig1/CCLE/17-AAG.RDS') + 
  theme(plot.title=element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
    scale_color_brewer(palette = 'Dark2') + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,1),labels=c('0','1'),limits = c(0,1), name='Density')
p6 <- readRDS('Figs/Fig1/GDSC/17-AAG.RDS') + 
  theme(plot.title=element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
    scale_color_brewer(palette = 'Dark2') + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,1),labels=c('0','1'),limits = c(0,1), name='Density') +
  ggpubr::rotate()
ggdraw() +
  draw_plot(p1, 0, .6, .3, .4) +
  draw_plot(p2, .32, .56, .68, .44) + 
  draw_plot(p3, 0, 0, .4, .55) + 
  draw_plot(p4,.4,0,.5,.45) +
  draw_plot(p5,.445,.45,.455,.1) +
  draw_plot(p6,.9,.045,.08,.405) + 
  draw_plot_label(c("(a)", "(b)","(c)", "(d)"), c(0,.32,0,.4), c(1,1,.55,.55), size = 14) 
ggsave('Figs/Figure_1.pdf',width=12,height=8.5)
```

Figure 2.
```{r}
p2_1 <- readRDS('Figs/Fig2/Spearman_LOR_CCLE_GDSC.RDS') + 
  scale_color_brewer(palette = 'Dark2') + 
  theme(legend.position = 'none') + 
  theme(axis.title = element_text(size = 14),
        plot.title = element_text(size=14),
        axis.text = element_text(size = 12)) + 
  ggtitle('Pairwise study agreement') +
  geom_hline(aes(yintercept=0),lty=2,lwd=.8,alpha=.5) +
  geom_vline(aes(xintercept=0),lty=2,lwd=.8,alpha=.5)
p2_2 <- readRDS('Figs/Fig2/Nilotinib_posterior_CCLE_GDSC.RDS') + 
  theme(legend.position = c(.1,.65), 
        plot.title=element_blank()) + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  geom_hline(aes(yintercept=.4),lty=2,lwd=.8,alpha=.5) +
  geom_vline(aes(xintercept=.4),lty=2,lwd=.8,alpha=.5)
p2_3 <- readRDS('Figs/Fig2/CCLE/Nilotinib.RDS') + 
  theme(plot.title=element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
    scale_color_brewer(palette = 'Dark2') + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,1),labels=c('0','1'),limits = c(0,1), name='Density')
p2_4 <- readRDS('Figs/Fig2/GDSC/Nilotinib.RDS') + 
  theme(plot.title=element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
    scale_color_brewer(palette = 'Dark2') + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,1),labels=c('0','1'),limits = c(0,1), name='Density') +
  ggpubr::rotate()

ggdraw() +
  draw_plot(p2_1, 0, 0, .4, 1) + 
  draw_plot(p2_2,.42,0,.5,.85) +
  draw_plot(p2_3,.46,.85,.46,.15) +
  draw_plot(p2_4,.92,.07,.08,.78) + 
  draw_plot_label(c("(a)", "(b)"), c(0,.42), c(1,1), size = 14) 
ggsave('Figs/Figure_2.pdf',width=12,height=6)

p3 <- p3 + theme(plot.title = element_blank())
p2_1 <- p2_1 + theme(plot.title = element_blank())

ggdraw() +
  draw_plot(p1, 0, .7, .3, .3) +
  draw_plot(p2, .32, .66, .68, .34) + 
  draw_plot(p3, 0, .325, .4, .325) + 
  draw_plot(p4,.425,.325,.475,.25) +
  draw_plot(p5,.47,.58,.43,.075) +
  draw_plot(p6,.9,.36,.08,.215) +
  draw_plot(p2_1, 0, 0, .4, .325) + 
  draw_plot(p2_2,.425,0,.475,.25) +
  draw_plot(p2_3,.47,.255,.43,.075) +
  draw_plot(p2_4,.9,.035,.08,.215) +
  draw_plot_label(c("(a)", "(b)","(c)", "(d)","(e)", "(f)"), c(0,.31,0,.43,0,.43), c(1,1,.66,.66,.34,.34), size = 14) 
ggsave('Figs/Figure_1_combined.pdf',width=12,height=12)

```

Figure 3.
```{r}
p1 <- readRDS('Figs/Fig3/p_prior_smoothed.RDS') +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size=14)) +
  geom_vline(aes(xintercept=.1),lty=2,lwd=.8,alpha=.5) +
  scale_fill_brewer(palette = 'Accent')
p2 <- readRDS('Figs/Fig3/boxplot_raw_all_drugs_prior.RDS')  + 
  labs(y='AOC') + 
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size=14),
        strip.text.x = element_text(size=14)) +
  scale_fill_brewer(palette = 'Dark2') + 
  geom_hline(aes(yintercept=.4),lty=2,lwd=.5)
p3 <- readRDS('Figs/Fig3/posterior_drug_types.RDS') +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position='none',
        plot.title = element_text(size=14),
        strip.text.x = element_text(size=14)) + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_color_brewer(palette = 'Dark2')
p4 <- readRDS('Figs/Fig3/posterior_drug_types_individual.RDS')  +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position='none',
        plot.title = element_text(size=14)) +
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_color_brewer(palette = 'Dark2')
ggdraw() +
  draw_plot(p1, 0, .49, .3, .51) +
  draw_plot(p2, .3, .53, .7, .47) + 
  draw_plot(p3, 0, 0, .48, .5) + 
  draw_plot(p4, .5, 0, .48, .5) +
  draw_plot_label(c("(a)", "(b)","(c)","(d)"), c(0,.3,0,.5), c(1,1,.5,.5), size = 14) 
ggsave('Figs/Figure_3.pdf',width=12,height=8.5)
```

Figure 4.
```{r}
p1 <- readRDS('Figs/Fig4/ccle/TAE684.RDS') + 
  facet_wrap(vars(experiment)) + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size=14),
        plot.title = element_blank()) + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) + 
  scale_color_brewer(palette = 'Dark2')
p2 <- readRDS('Figs/Fig4/ccle/TAE684_qq.RDS')  + 
  facet_wrap(vars(experiment)) + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size=14),
        plot.title = element_blank()) + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) + 
  scale_color_brewer(palette = 'Dark2')
p3 <- readRDS('Figs/Fig4/TAE684_posterior_CCLE_GDSC.RDS')  + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        plot.title = element_text(size=14),
        legend.position = 'right',legend.text = element_text(size=12)) + 
  ggtitle(label='TAE684 Posterior Agreement') +
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) + 
  scale_fill_brewer(palette = 'Dark2')
p4 <- readRDS('Figs/Fig4/gdsc/TAE684.RDS')  + 
  facet_wrap(vars(experiment)) + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size=14),
        plot.title = element_blank()) + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) + 
  scale_color_brewer(palette = 'Dark2')
p5 <- readRDS('Figs/Fig4/gdsc/TAE684_qq.RDS') + 
  facet_wrap(vars(experiment)) + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size=14),
        plot.title = element_blank()) + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) + 
  scale_color_brewer(palette = 'Dark2')
p6 <- readRDS('Figs/Fig4/ccle/paclitaxel.RDS') + 
  facet_wrap(vars(experiment)) + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size=14),
        plot.title = element_blank()) + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) + 
  scale_color_brewer(palette = 'Dark2')
p7 <- readRDS('Figs/Fig4/ccle/paclitaxel_qq.RDS') + 
  facet_wrap(vars(experiment)) + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size=14),
        plot.title = element_blank()) + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) + 
  scale_color_brewer(palette = 'Dark2')
p8 <- readRDS('Figs/Fig4/paclitaxel_posterior_CCLE_GDSC.RDS')  + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        plot.title = element_text(size=14),
        legend.position = 'right',legend.text = element_text(size=12)) + 
  ggtitle(label='Paclitaxel Posterior Agreement') +
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) + 
  scale_fill_brewer(palette = 'Dark2')
p9 <- readRDS('Figs/Fig4/gdsc/paclitaxel.RDS') + 
  facet_wrap(vars(experiment)) + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size=14),
        plot.title = element_blank()) + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) + 
  scale_color_brewer(palette = 'Dark2')
p10 <- readRDS('Figs/Fig4/gdsc/paclitaxel_qq.RDS') + 
  facet_wrap(vars(experiment)) + 
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size=14),
        plot.title = element_blank()) + 
  scale_x_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) +
  scale_y_continuous(breaks=c(0,.5,1),labels=c('0','0.5','1'),limits = c(0,1)) + 
  scale_color_brewer(palette = 'Dark2')

ggdraw() +
  draw_plot(p1, 0, .7, .22, .28) +
  draw_plot(p2, .25, .7, .22, .28) + 
  draw_plot(p3, .05, .3, .45, .4) + 
  draw_plot(p4, 0, 0, .22, .28) +
  draw_plot(p5, .25, 0, .22, .28) + 
  draw_plot(p6, .5, .7, .22, .28) +
  draw_plot(p7, .75, .7, .22, .28) + 
  draw_plot(p8, .55, .3, .45, .4) + 
  draw_plot(p9, .5, 0, .22, .28) +
  draw_plot(p10, .75, 0, .22, .28) +
  draw_line(x = c(0.5, 0.5),y = c(0, 1),color = "black", size = .5,alpha=.8,lty=1) +
  draw_plot_label(c("(a)", "(b)","(c)","(d)","(e)","(f)"), c(0,0,0,.5,.5,.5), c(1,.7,.28,1,.7,.28), size = 14) 
ggsave('Figs/Figure_4.pdf',width=12,height=8.5)
```

Figure 5.
```{r}
p2 <- readRDS('Figs/Fig5/pairwise_cell_agreements.RDS') +
  theme(legend.position = 'right') + 
  theme(axis.title = element_blank(),
        legend.text = element_text(size=12),
        legend.title = element_text(size=14),
        plot.title = element_text(size=14),
        axis.text = element_text(size = 12),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        strip.text.x = element_text(size=14)) +
  scale_fill_brewer(palette = 'Accent') + 
  labs(y='',x='') + 
  ggtitle('Pairwise posterior probability of cell agreement') + 
  facet_wrap(vars(Drug_type),nrow=1,scales='free')
p3 <- readRDS('Figs/Fig5/pairwise_drug_agreements.RDS') +
  theme(legend.position = 'none') + 
  theme(axis.title = element_blank(),
        plot.title = element_text(size=14),
        axis.text = element_text(size = 12)) +
  scale_fill_brewer(palette = 'Accent') + 
  labs(y='Posterior probability',x='Drug type') + 
  ggtitle('Pairwise posterior probability of drug agreement')
p4 <- readRDS('Figs/Fig5/pairwise_study_agreements_broad.RDS')  +
  theme(legend.position = 'right') + 
  theme(axis.title = element_text(size = 14),
        legend.text = element_text(size=12),
        legend.title = element_text(size=14),
        plot.title = element_text(size=14),
        axis.text = element_text(size = 12)) +
  scale_fill_brewer(palette = 'Accent') + 
  labs(y='Pearson',x='Spearman') + 
  ggtitle('Pairwise study agreement') +
  geom_hline(aes(yintercept=0),lty=2,lwd=.8,alpha=.5) +
  geom_vline(aes(xintercept=0),lty=2,lwd=.8,alpha=.5)
p5 <- readRDS('Figs/Fig5/pairwise_study_agreements_targeted.RDS') +
  theme(legend.position = 'none') + 
  theme(axis.title = element_text(size = 14),
        plot.title = element_text(size=14),
        axis.text = element_text(size = 12)) +
  scale_fill_brewer(palette = 'Accent') + 
  labs(y='Log-odds ratio',x='Spearman') + 
  ggtitle('Pairwise study agreement') +
  geom_hline(aes(yintercept=0),lty=2,lwd=.8,alpha=.5) +
  geom_vline(aes(xintercept=0),lty=2,lwd=.8,alpha=.5)
ggdraw() +
  draw_plot(p2, 0, .5, .55, .5) +
  draw_plot(p3, .55, .5, .45, .5) + 
  draw_plot(p4, 0, 0, .56, .5) + 
  draw_plot(p5, .56, 0, .44, .5) +
  draw_plot_label(c("(a)", "(b)","(c)","(d)"), c(0,.55,0,.56), c(1,1,.5,.5), size = 14) 
ggsave('Figs/Figure_5.pdf',width=12,height=8.5)
```
